# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

# Guards to prevent enabling mutually-exclusive modules simultaneously.
# `checkDns` and `checkBoot` are evaluated in the `let` below and will
# abort evaluation with a clear error message if violated.

let
  # DNS configuration guards
  usingResolved = config.services.resolved.enable or false;
  usingDnsmasq  = config.services.dnsmasq.enable or false;
  usingClassic  = ((config.networking.nameservers or []) != []) && !(usingResolved || usingDnsmasq);

  # Bootloader configuration guards
  usingSystemdBoot = config.boot.loader.systemd-boot.enable or false;
  usingLanzaboote  = config.boot.lanzaboote.enable or false;

  # Guard evaluations
  checkDns  = if (!(usingResolved && usingDnsmasq) && !(usingResolved && usingClassic) && !(usingDnsmasq && usingClassic)) then true else builtins.error "Only one of dns-resolved, dns-dnsmasq or dns-classic may be enabled";
  checkBoot = if (!(usingSystemdBoot && usingLanzaboote)) then true else builtins.error "Enable either systemd-boot or boot-secure (lanzaboote), not both";
in

{
  imports =
    [
      # Hardware configuration generated by `nixos-generate-config` (but modified)
      ./modules/hardware-configuration.nix

      # Rampart option declarations - must be connected higher than used
      ./modules/rampart-options.nix    # Rampart option declarations

      # Boot modules (choose ONE)
      ./modules/boot.nix               # Standard boot configuration
    # ./modules/boot-secure.nix        # Secure Boot with Lanzaboote

      # System modules
    # ./modules/kernel.nix             # Kernel parameters, modules and sysctl settings
      ./modules/memory.nix             # Anything related to system memory (RAM)
      ./modules/entropy.nix            # Entropy / RNG configuration
      ./modules/filesystems.nix        # Filesystem-related sysctl and ntfs support
    # ./modules/apparmor.nix           # AppArmor MAC configuration
    # ./modules/usbguard.nix           # USB device authorization

      # Networking modules
      ./modules/networking.nix         # General networking configuration

      # DNS configuration modules (choose ONE)
      ./modules/dns-classic.nix        # Classic static DNS configuration (conflicts with resolved and dnsmasq)
    # ./modules/dns-resolved.nix       # DNSSEC DNS with systemd-resolved (conflicts with classic and dnsmasq)
    # ./modules/dns-dnsmasq.nix        # Alternative: DNSSEC DNS with dnsmasq (conflicts with classic and resolved)

      # Application modules
    # ./modules/chromium.nix           # Ungoogled Chromium browser configuration (conflicts with chromium-firejail and it will also not work with the memory.nix module if the hardened allocator is enabled in it)
      ./modules/chromium-firejail.nix  # Ungoogled Chromium with Firejail sandboxing (configuration conflicts with regular chromium.nix module)
      ./modules/veracrypt.nix          # VeraCrypt disk encryption

      ./modules/localization.nix       # Localization settings
      ./modules/desktop.nix            # Desktop environment settings
      ./modules/users.nix              # User accounts and permissions

      # Privilege escalation modules (choose ONE)
      ./modules/sudo.nix               # Sudo security configuration (traditional, feature-rich)
    # ./modules/doas.nix               # Doas security configuration (OpenBSD alternative: simpler, smaller attack surface)

      ./modules/packages.nix           # Additional system packages
      ./modules/nixos-permissions.nix  # Secure /etc/nixos/ permissions
    # ./modules/ssh.nix                # SSH server/client configuration 
    # ./modules/virtualisation.nix     # Virtualization settings
    
      # Finalizer for kernel arrays/sysctl - must be last so it sees additions
      ./modules/kernel-finalize.nix
    ];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # Did you read the comment?
}
